model:
  target: ultrashape.pipelines.UltraShapePipeline
  params:
    # 1. VAE Config (small)
    vae_config:
      target: ultrashape.models.autoencoders.ShapeVAE
      params:
        num_latents: &token_num 2048
        embed_dim: 64
        num_freqs: 8
        include_pi: false
        heads: 16
        width: 1024
        point_feats: 4
        num_encoder_layers: 8
        num_decoder_layers: 16
        pc_size: 409600 # num_s (204800) + num_u (204800)
        pc_sharpedge_size: 0
        downsample_ratio: 20
        qkv_bias: false
        qk_norm: true
        scale_factor: 1.0039506158752403
        geo_decoder_mlp_expand_ratio: 4
        geo_decoder_downsample_ratio: 1
        geo_decoder_ln_post: true
        enable_flashvdm: true
        jitter_query: false
        voxel_query: true
        voxel_query_res: 128

    # 2. DiT Denoiser Config (small)
    dit_cfg:
      target: ultrashape.models.denoisers.dit_mask.RefineDiT
      params:
        input_size: *token_num
        in_channels: 64
        hidden_size: 1536
        context_dim: 768
        depth: 12
        num_heads: 12
        qk_norm: true
        text_len: 730
        qk_norm_type: 'rms'
        qkv_bias: false
        num_moe_layers: 2
        num_experts: 4
        moe_top_k: 1

    # 3. Image Encoder Config (small)
    conditioner_config:
      target: ultrashape.models.conditioner_mask.SingleImageEncoder
      params:
        drop_ratio: 0.0
        main_image_encoder:
            type: DinoImageEncoder
            kwargs:
                version: 'facebook/dinov2-base'
                image_size: 384
                use_cls_token: true

    # 4. Scheduler Config
    scheduler_cfg:
      target: ultrashape.schedulers.FlowMatchEulerDiscreteScheduler
      params:
        num_train_timesteps: 1000

    # 5. Image Processor
    image_processor_cfg:
      target: ultrashape.preprocessors.ImageProcessorV2
      params:
        size: 384
