name: "UltraShape Refine VAE"

training:
  # ckpt_path:
  steps: 1150
  use_amp: true
  amp_type: "bf16"
  base_lr: 1e-5
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"
  every_n_train_steps: 23
  val_check_interval: 23
  log_every_n_steps: 10
  limit_val_batches: 1.0

callbacks:
  early_stop:
    target: pytorch_lightning.callbacks.EarlyStopping
    params:
      monitor: "val/total_loss"
      mode: "min"
      patience: 5
      min_delta: 0.0

dataset:
  target: ultrashape.data.objaverse_vae.ObjaverseDataModule
  params:
    batch_size: 4
    num_workers: 2
    val_num_workers: 2

    # data
    training_data_list: data/dataset
    sample_pcd_dir: data/dataset/sample

    # input_pcd
    pc_size: &pc_size 65536
    pc_sharpedge_size: &pc_sharpedge_size 0
    sharpedge_label: &sharpedge_label true
    return_normal: true

    # sup_pcd
    sup_near_uni_size: 32768
    sup_near_sharp_size: 32768
    sup_space_size: 32768
    tsdf_threshold: 0.01

model:
  target: ultrashape.models.autoencoders.VAETrainer
  params:
    ckpt_path: null
    torch_compile: false
    save_dir: outputs/vae_recon
    mc_res: 128
    vae_config:
      target: ultrashape.models.autoencoders.ShapeVAE
      params:
        num_latents: &num_latents 2048 # reduced for lower memory
        embed_dim: 64
        num_freqs: 8
        include_pi: false
        heads: 16
        width: 1024
        point_feats: 4
        num_encoder_layers: 8
        num_decoder_layers: 16
        pc_size: *pc_size
        pc_sharpedge_size: *pc_sharpedge_size
        downsample_ratio: 20
        qkv_bias: false
        qk_norm: true
        geo_decoder_mlp_expand_ratio: 4
        geo_decoder_downsample_ratio: 1
        geo_decoder_ln_post: true
        enable_flashvdm: true
        jitter_query: true

    optimizer_cfg:
      optimizer:
        target: torch.optim.AdamW
        params:
          betas: [0.9, 0.99]
          eps: 1.e-6
          weight_decay: 1.e-2

      scheduler:
        target: ultrashape.utils.trainings.lr_scheduler.LambdaWarmUpCosineFactorScheduler
        params:
          warm_up_steps: 50 # 5000
          f_start: 1.e-6
          f_min: 1.e-3
          f_max: 1.0

    loss_cfg:
      lambda_logits: 1.
      lambda_kl: 0.001
      # lambda_eik: -1.
      # lambda_sn: -1.
      # lambda_sign: -1.
